SYSTEM:
    NUM_WORKERS: 0
    DEVICE: 'cpu'
    global_data_root: '../../global_data/'
DATA:
    dataset_name: "waybill"
    data_root: './local_data/waybill/'

MODEL:
    embed_dim: 300
    num_classes: 2
    init_embed_with_glove: False
    hidden_n: 128
    dropout: 0.1
    num_layers: 1

TRAIN:
    num_train_epochs: 40
    learning_rate: 0.001
    lr_decay_gamma: 0.2
    milestones: [10, 20]
    milestones_in_epo: True
    warmup_steps: 500
    batch_size: 16
    early_stop_n: 4
    save_dir: './exp/lstm_crf/'