DATA:
  data_root: ./local_data/waybill/
  dataset_name: waybill
  min_freq: 1
MODEL:
  dropout: 0.1
  embed_dim: 300
  hidden_n: 128
  init_embed_with_glove: false
  max_seq_len: 50
  model_name: Text_CNN
  num_classes: 2
  num_layers: 1
  rnn_type: LSTM
SYSTEM:
  DEVICE: cpu
  NUM_WORKERS: 0
  global_data_root: ../../global_data/
TEST:
  batch_size: 256
  model_load_path: ''
  save_dir: ''
TRAIN:
  adam_epsilon: 1.0e-06
  batch_size: 16
  early_stop_n: 4
  gradient_accumulation_steps: 1
  learning_rate: 0.001
  load_from: ''
  log_steps: 200
  lr_decay_gamma: 0.2
  milestones:
  - 10
  - 20
  milestones_in_epo: true
  num_train_epochs: 40
  save_dir: ./exp/lstm_crf/
  warmup_steps: 500
  weight_decay: 0.0

